config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  resource :session, only: [:new, :create, :destroy]

  root to: redirect("/cats")

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password
  validates :session_token, presence: true

  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to :cats_url
    else
      render json: @user.error.full_messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1> </h1>

<form action="<%= session_url %>" method="post">
  <label for="username">username</label>
  <input id="username" type="text" name="user[user_name]" value="<% @user.user_name%>">

  <br>

  <label for="password">Password</label>
  <input id="password" type="text" name="user[password]" value="<% @user.password%>">

  <input type="submit">
</form>